<template>
  <div
    grid 
    gap-4 
    grid-cols-2
  >
    <!-- upper box keep this?? change it? -->
    <Skeletor 
      height="70"
      width="100%"
      class="
      grid
      gap-4
      grid-cols-2"
    />
    <!-- Left side skeleton -->
    <div
      class="
    grid
    gap-4
    grid-cols-2"
    >
      <div>
        <Skeletor 
          height="20%"
          width="40%"
          class="
        mt-5
        my-2
        ml-10"
        />
        <Skeletor 
          height="10%"
          width="70%"
          class="
        ml-10"
        />
        
        <Skeletor 
          height="10%"
          width="90%"
          class="
        ml-10
        my-2"
        />
        <Skeletor 
          height="5%"
          width="70%"
          class="
        ml-10
        mb-3"
        />
        <Skeletor 
          height="15%"
          width="70%"
          class="
        ml-10
        my-2"
        />
        <Skeletor 
          height="15%"
          width="70%"
          class="
        ml-10
        my-2"
        />
        <Skeletor 
          height="15%"
          width="70%"
          class="
        ml-10
        my-2"
        />
        <Skeletor 
          height="15%"
          width="70%"
          class="
        ml-10
        my-2"
        />
        <Skeletor 
          height="15%"
          width="70%"
          class="
        ml-10
        my-2"
        />
        <Skeletor 
          height="15%"
          width="70%"
          class="
        ml-10
        my-2"
        />
        <Skeletor 
          height="40%"
          width="20%"
          class="
        mt-5
        my-2
        ml-10"
        />
      </div>
      <!-- Right side Skeleton -->
      <div> 
        <Skeletor 
          height="35%"
          width="40%"
          class="
        mt-5
        my-2
        ml-5"
        />
        <Skeletor 
          height="15%"
          width="80%"
          class="
        ml-5"
        />
        <Skeletor 
          height="25%"
          width="90%"
          class="
        ml-5
        my-2"
        />
        <Skeletor 
          height="15%"
          width="70%"
          class="
        ml-5
        my-2"
        />
        <Skeletor 
          height="15%"
          width="70%"
          class="
        ml-5
        my-2"
        />
        <Skeletor 
          height="15%"
          width="70%"
          class="
        ml-5
        my-2"
        />
        <Skeletor 
          height="15%"
          width="70%"
          class="
        ml-5
        my-2"
        />
        <Skeletor 
          height="15%"
          width="70%"
          class="
        ml-5
        my-2"
        />
        <Skeletor 
          height="15%"
          width="70%"
          class="
        ml-5
        my-2"
        />
        <Skeletor 
          height="15%"
          width="70%"
          class="
        ml-5
        my-2"
        />
        <Skeletor 
          height="15%"
          width="70%"
          class="
        ml-5
        my-2"
        />
        <Skeletor 
          height="40%"
          width="20%"
          class="
        mt-5
        my-2
        ml-5"
        />
      </div>
    </div>
  </div>
</template>

<script>
import { Skeletor } from 'vue-skeletor';
import 'vue-skeletor/dist/vue-skeletor.css';

export default {
  components: {
    Skeletor

  }
};
</script>
